name: timemil
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.7.15=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.18=h955ad1f_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - adamp==0.3.0
      - aeon==0.9.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.1.8
      - deprecated==1.2.18
      - dtaidistance==2.3.13
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - fsspec==2025.3.0
      - git-filter-repo==2.47.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - joblib==1.4.2
      - llvmlite==0.41.1
      - numba==0.58.1
      - numpy==1.24.4
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.4.0
      - protobuf==5.29.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.43.0
      - six==1.17.0
      - smmap==5.0.2
      - threadpoolctl==3.5.0
      - timm==0.9.16
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - tslearn==0.6.4
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - wandb==0.22.3
      - wrapt==1.17.3
prefix: /home/moon/anaconda3/envs/timemil
